### ISSUE TITLE
[costmap_2d] Loss of data in the pointcloud during transformation from sensor_frame to global_frame in ObservationBuffer class

### ISSUE THREAD

**Issue by s-niket** [ros-planning/navigation#1113]
Hi, 

I have setup my robot with a 2D LiDAR sensor with the move_base and I am having difficulties in generating the local_costmap. The configuration files are as below. 

Upon publishing the transformed pointcloud from the ObservationBuffer object in the ObstacleLayer class in the updateBounds method, I observed that that only half of the actual data was present in the message.

https://github.com/ros-planning/navigation/blob/noetic-devel/costmap_2d/src/observation_buffer.cpp#L108-L139

I verified the frame values and they were correct. Any ideas why this would happen? 

global_costmap_params.yaml

```
global_costmap:
   global_frame: map
   robot_base_frame: base_link
   update_frequency: 1.0
   publish_frequency: 0.5
   static_map: true
   transform_tolerance: 0.5
   rolling_window: false
   plugins:
     - {name: static_layer,            type: "costmap_2d::StaticLayer"}
     - {name: obstacle_layer,          type: "costmap_2d::ObstacleLayer"}
     - {name: inflation_layer,         type: "costmap_2d::InflationLayer"}

   static_layer:       
      enabled: true 
      map_topic: map 
      subscribe_to_updates: true

   obstacle_layer:
      observation_sources:  scan 
      scan: {sensor_frame: base_link, data_type: LaserScan, topic: /scan, marking: true, clearing: true}

   inflation_layer:
      enabled: true
      inflation_radius: 0.3
      cost_scaling_factor: 5.0
```

local_costmap_params.yaml

```
local_costmap:
   global_frame: odom
   robot_base_frame: base_link
   update_frequency: 5.0
   publish_frequency: 5.0
   static_map: false
   rolling_window: true
   width: 5.0
   height: 5.0
   resolution: 0.05
   transform_tolerance: 0.1
   combination_method: 0
   plugins:
    - {name: obstacle_layer,      type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer,     type: "costmap_2d::InflationLayer"}


   obstacle_layer:
      enabled: true
      obstacle_range: 5.0
      raytrace_range: 5.0
      max_obstacle_height: 3
      min_obstacle_height: 0
      observation_sources:  scan 
      scan: {sensor_frame: base_link, data_type: LaserScan, topic: /scan, marking: true, clearing: true}

   inflation_layer:
      enabled: true
      inflation_radius: 0.3
      cost_scaling_factor: 5.0
```

quadcopter_move_base.launch

```
<!--
    ROS navigation stack with velocity smoother and safety (reactive) controller
-->
<launch>
  <!--<include file="$(find quadrotor_navigation)/launch/includes/velocity_smoother.launch.xml"/>-->
  <!--<include file="$(find quadrotor_navigation)/launch/includes/safety_controller.launch.xml"/>-->
  <!-- <include file="$(find quadrotor_navigation)/launch/quadrotor_localization.launch"/> -->

  <!--<arg name="odom_frame_id"   default="world"/>-->
  <arg name="odom_frame_id"   default="odom"/>
  <arg name="base_frame_id"   default="base_link"/>
  <arg name="global_frame_id" default="map"/>
  <!--<arg name="odom_topic" default="/ground_truth/state" />-->
  <arg name="odom_topic" default="/cat_dog/odometry" />
  <arg name="laser_topic" default="/cat_dog/corrected_lidar_scan" />
  <arg name="custom_param_file" default="$(find quadrotor_navigation)/param/dummy.yaml"/>

  <node pkg="move_base" type="move_base" respawn="false" name="move_base" output="screen">
    <rosparam file="$(find quadrotor_navigation)/param/costmap_common_params.yaml" command="load" ns="global_costmap" />
    <rosparam file="$(find quadrotor_navigation)/param/costmap_common_params.yaml" command="load" ns="local_costmap" />
    <rosparam file="$(find quadrotor_navigation)/param/local_costmap_params.yaml" command="load" />
    <rosparam file="$(find quadrotor_navigation)/param/global_costmap_params.yaml" command="load" />
    <rosparam file="$(find quadrotor_navigation)/param/dwa_local_planner_params.yaml" command="load" />
    <rosparam file="$(find quadrotor_navigation)/param/move_base_params.yaml" command="load" />
    <rosparam file="$(find quadrotor_navigation)/param/global_planner_params.yaml" command="load" />
    <rosparam file="$(find quadrotor_navigation)/param/navfn_global_planner_params.yaml" command="load" />
    <!-- external params file that could be loaded into the move_base namespace -->
    <rosparam file="$(arg custom_param_file)" command="load" />

    <!-- reset frame_id parameters using user input data -->
    <param name="global_costmap/global_frame" value="$(arg global_frame_id)"/>
    <param name="global_costmap/robot_base_frame" value="$(arg base_frame_id)"/>
    <param name="local_costmap/global_frame" value="$(arg odom_frame_id)"/>
    <param name="local_costmap/robot_base_frame" value="$(arg base_frame_id)"/>
    <param name="DWAPlannerROS/global_frame_id" value="$(arg odom_frame_id)"/>

    <remap from="cmd_vel" to="/cmd_vel"/>
    <remap from="odom" to="$(arg odom_topic)"/>
    <remap from="scan" to="$(arg laser_topic)"/>
  </node>
</launch>

```
The result causes the local_costmap to not update in the apparent blind spot. 

Here are some images from RViz outputs:

https://drive.google.com/file/d/1lzLytuZi0IN-nGGicddwgB5wXsBbJ6Iv/view?usp=sharing

https://drive.google.com/file/d/1KOBDqsh5SjLJyHtXDh2mVjNZn3CCqzv4/view?usp=sharing

https://drive.google.com/file/d/1IweSaX5EKuy9a0xKIBfyEvJ9W8j6SZ5v/view?usp=sharing
