### ISSUE TITLE
Groovy config files cause update rate problem under Hydro

### ISSUE THREAD

**Issue by pirobot** [ros-planning/navigation#151]
My setup: Ubuntu 12.04 + ROS Hydro Debian installation

I am trying a simple navigation test under Hydro for the first time using a blank map and a fake TurtleBot. (I use the arbotix_ros package in 'sim' model to drive the fake robot.)  My navigation config files work fine under Groovy and I can send the robot any number of move_base goals successfully.  However, when I switch my workspace to Hydro and try the same config files (in compatibility mode) to send a simple move_base goal to the fake robot, I immediately get the following warnings in the move_base server window:

[ WARN] [1384522937.760447239]: Control loop missed its desired rate of 3.0000Hz... the loop actually took 0.8339 seconds
[ WARN] [1384522937.760639048]: Map update loop missed its desired rate of 5.0000Hz... the loop actually took 0.6339 seconds

and the robot never reaches the goal but instead wanders about near the goal.

My test move_base goal command is:

$ rostopic pub -1 /move_base_simple/goal geometry_msgs/PoseStamped '{ header: { frame_id: "base_link" }, pose: { position: { x: 1.0, y: 0, z: 0 }, orientation: { x: 0, y: 0, z: 0, w: 1 } } }'

and my config files are as follows:

costmap_common_params.yaml

```
obstacle_range: 2.5
raytrace_range: 3.0
robot_radius: 0.15
inflation_radius: 0.3
max_obstacle_height: 0.6
min_obstacle_height: 0.0
observation_sources: scan
scan: {data_type: LaserScan, topic: /scan, marking: true, clearing: true, expected_update_rate: 0}
```

base_local_planner_params.yaml

```
controller_frequency: 3.0
recovery_behavior_enabled: false
clearing_rotation_allowed: false

TrajectoryPlannerROS:
   max_vel_x: 0.5
   min_vel_x: 0.1
   max_rotational_vel: 1.0
   min_in_place_vel_theta: 0.4
   escape_vel: -0.1
   acc_lim_x: 2.5
   acc_lim_y: 2.5
   acc_lim_th: 3.2

   holonomic_robot: false
   yaw_goal_tolerance: 0.1 # about 6 degrees
   xy_goal_tolerance: 0.05  # 5 cm
   latch_xy_goal_tolerance: false
   pdist_scale: 0.8
   gdist_scale: 0.4
   meter_scoring: true

   heading_lookahead: 0.325
   heading_scoring: false
   heading_scoring_timestep: 0.8
   occdist_scale: 0.1
   oscillation_reset_dist: 0.05
   publish_cost_grid_pc: false
   prune_plan: true

   sim_time: 1.0
   sim_granularity: 0.025
   angular_sim_granularity: 0.025
   vx_samples: 50
   vtheta_samples: 200
   dwa: true
   simple_attractor: false
```

local_costmap_params.yaml

```
local_costmap:
   global_frame: /odom
   robot_base_frame: /base_footprint
   update_frequency: 5.0
   publish_frequency: 1.0
   static_map: true
   rolling_window: false
   width: 5.0
   height: 5.0
   resolution: 0.01
   transform_tolerance: 1.0
   map_type: costmap
```

global_costmap_params.yaml

```
global_costmap:
   global_frame: /map
   robot_base_frame: /base_footprint
   update_frequency: 5.0
   publish_frequency: 1.0
   static_map: true
   rolling_window: false
   resolution: 0.01
   transform_tolerance: 1.0
   map_type: costmap
```
