### ISSUE TITLE
local_planner's control loop is executed very slow on PR2 hydro

### ISSUE THREAD

**Issue by furushchev** [ros-planning/navigation#361]
I'm using PR2 robot on ROS Hydro.
On passing navigation goal, it fails to meet the control loop speed of 10Hz (on my PR2 env, it takes about 1.3 sec on each local control loop), resulting in choppy motion and poor navigation.
I profiled which function wastes time the most, and found it is `MapGrid::computeTargetDistance`.
This function has a `while` loop, which loops 1421744 times. (approx: 0.25 sec)
How could it be faster, or what is the problem to make navigation slow down?

Update: Below is my params

``` yaml
$ rosparam get /move_base_node/DWAPlannerROS/ -p
acc_lim_th: 3.2
acc_lim_theta: 3.2
acc_lim_x: 2.5
acc_lim_y: 2.5
acc_limit_trans: 0.1
angular_sim_granularity: 0.1
forward_point_distance: 0.325
goal_distance_bias: 32.0
max_rot_vel: 1.0
max_scaling_factor: 0.2
max_trans_vel: 0.4
max_vel_x: 0.4
max_vel_y: 0.1
min_rot_vel: 0.4
min_trans_vel: 0.1
min_vel_x: 0.0
min_vel_y: -0.1
occdist_scale: 0.01
oscillation_reset_angle: 0.2
oscillation_reset_dist: 0.05
path_distance_bias: 24.0
prune_plan: false
restore_defaults: false
rot_stopped_vel: 0.01
scaling_speed: 0.25
sim_granularity: 0.1
sim_period: 0.1
sim_time: 1.0
stop_time_buffer: 0.2
trans_stopped_vel: 0.01
use_dwa: true
vth_samples: 20
vtheta_samples: 5
vx_samples: 3
vy_samples: 10
xy_goal_tolerance: 0.2
yaw_goal_tolerance: 0.17
```
