### ISSUE TITLE
Global Costmap is not static anymore (although static is enabled)

### ISSUE THREAD

**Issue by ssrselvamraju** [ros-planning/navigation#432]
After the upgrade to Navstack 1.12.7 from 1.12.4, we're now experiencing the following issues:
1. In 1.12.4 I didn't have to specify the width and height of the global costmap, and it was automatically picking up to be the size of the actual "map". After the 1.12.7 upgrade seems like I'm having to set the height and width (discovered this, when the global costmap was defaulting to size of 10x10 after the navstack upgrade)
2. Although the height and width is set to 10,000x10,000 the size seems to be shrinking based on the distance the robot is travelling, so if there's a goal position set to a different point in the map which is now not in the global costmap, the robot is unable to plan there.

Global costmap with navstack 1.12.7 (and height X width = 10,000 x 10,000)

![image](https://cloud.githubusercontent.com/assets/3400029/13720086/e8f3aaa4-e7b4-11e5-96c4-fdf76c19d23a.png)

Global costmap with navstack 1.12.4 (and height X width is not explicitly set anywhere, but default params are 10x10. Also publish frequency is 0, since this is a static layer and doesn't have to update)

![image](https://cloud.githubusercontent.com/assets/3400029/13720060/810edeae-e7b4-11e5-9e24-29a0b603bb75.png)

Any suggestions/solutions for me to try?

**Comment by mirzashah** [comment]
I believe you're experiencing same issue I had #430 . I fell back to 1.12.5, the code breaks in 1.12.6

**Comment by mikeferguson** [comment]
Do either of you have a link to your navigation configuration? We're not seeing this issue in house, so I'm hoping to narrow down what you might be using that is different from our config.

**Comment by mikeferguson** [comment]
Also, a trace of the ROSOUT would be useful, in particular, if you see "Requesting the map..." or "Received a map.."

**Comment by ssrselvamraju** [comment]
$ cat costmap_common_params.yaml 

```
obstacle_range: 3.0
raytrace_range: 5.0
robot_radius: 0.5
inflation_radius: 0.5

observation_sources: velodyne_scan laser_scan_sensor laser_scan_sensor2 #laser_scan_sensor3

velodyne_scan: {sensor_frame: velodyne, data_type: LaserScan, topic: velodyne_scan, marking: true, clearing: true}


laser_scan_sensor: {sensor_frame: LMS151, data_type: LaserScan, topic: bottom_scan, marking: true, clearing: true}

laser_scan_sensor2: {sensor_frame: TiM551, data_type: LaserScan, topic: top_scan, marking: true, clearing: true}

#laser_scan_sensor3: {sensor_frame: LMS111, data_type: LaserScan, topic: back_scan, marking: true, clearing: true}

```

$ cat global_costmap_params.yaml 

```
global_costmap:
  map_type: costmap
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 5.0
  static_map: true
  track_unknown_space: true
  unknown_cost_value: 253

```

$ cat local_costmap_params.yaml 

```
local_costmap:
  map_type: costmap
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 10.0
  publish_frequency: 5.0
  static_map: false
  rolling_window: true
  width: 8.0
  height: 8.0
  resolution: 0.05

  cost_scaling_factor: 0.0

```

**Comment by ssrselvamraju** [comment]
@mikeferguson  A few traces of the logs:

First some grep:

```
~/.ros/log/b4f07922-e7ea-11e5-974e-78d00421308d$ grep "Requesting the map" *
move_base_delay-60-stdout.log:[ INFO] [1457743138.107876403]: Requesting the map...
move_base_delay-60-stdout.log:[ INFO] [1457989235.181643366]: Requesting the map...
rosout.log.1:1457989235.181657062 INFO [/navigation_stack/navigation-latest/costmap_2d/plugins/static_layer.cpp:87(StaticLayer::onInitialize) [topics: /rosout, /cmd_vel, /move_base/current_goal, /move_base/goal] Requesting the map...

:~/.ros/log/b4f07922-e7ea-11e5-974e-78d00421308d$ grep "Received a map" *

:~/.ros/log/b4f07922-e7ea-11e5-974e-78d00421308d$ grep "Received" *
move_base_delay-60-stdout.log:[ INFO] [1457743138.413897370]: Received a 1300 X 1300 map at 0.050000 m/pix
move_base_delay-60-stdout.log:[ INFO] [1457743137.033320141]: Received a 1300 X 1300 map @ 0.050 m/pix
move_base_delay-60-stdout.log:[ INFO] [1457989235.486678993]: Received a 1300 X 1300 map at 0.050000 m/pix
rosout.log.1:1457989235.486699380 INFO [/src/k5_navigation_stack/navigation-latest/costmap_2d/plugins/static_layer.cpp:99(StaticLayer::onInitialize) [topics: /rosout, /cmd_vel, /move_base/current_goal, /move_base/goal] Received a 1300 X 1300 map at 0.050000 m/pix
```

Here are some traces from the _move_base_delay-60-stdout.log_:

```
 * /move_base/loc^[[33m[ WARN] [1457743127.982014340]: Timed out waiting for transform from base_link to map to become available before running costmap, tf error: . canTransform returned after 0.10072 timeout was 0.1.^[[0m
^[[33m[ WARN] [1457743133.023318881]: Timed out waiting for transform from base_link to map to become available before running costmap, tf error: . canTransform returned after 0.100802 timeout was 0.1.^[[0m
^[[0m[ INFO] [1457743137.953746523]: Loading from pre-hydro parameter style^[[0m
^[[0m[ INFO] [1457743138.026017275]: Using plugin "static_layer"^[[0m
^[[0m[ INFO] [1457743138.107876403]: Requesting the map...^[[0m
^[[0m[ INFO] [1457743138.316194093]: Resizing costmap to 1300 X 1300 at 0.050000 m/pix^[[0m
^[[0m[ INFO] [1457743138.413897370]: Received a 1300 X 1300 map at 0.050000 m/pix^[[0m
^[[0m[ INFO] [1457743138.426256892]: Using plugin "obstacle_layer"^[[0m
^[[0m[ INFO] [1457743138.432730816]:     Subscribed to Topics: velodyne_scan laser_scan_sensor laser_scan_sensor2^[[0m
^[[0m[ INFO] [1457743138.545825845]: Using plugin "inflation_layer"^[[0m
^[[0m[ INFO] [1457743138.761383309]: Loading from pre-hydro parameter style^[[0m
^[[0m[ INFO] [1457743138.790227503]: Using plugin "obstacle_layer"^[[0m
^[[0m[ INFO] [1457743138.851336549]:     Subscribed to Topics: velodyne_scan laser_scan_sensor laser_scan_sensor2^[[0m
^[[0m[ INFO] [1457743138.914020751]: Using plugin "inflation_layer"^[[0m
^[[0m[ INFO] [1457743139.046973969]: Created local_planner base_local_planner/TrajectoryPlannerROS^[[0m
^[[0m[ INFO] [1457743139.060398137]: Sim period is set to 0.10^[[0m
^[[33m[ WARN] [1457743139.079141598]: You've specified a positive escape velocity. This is probably not what you want and will cause the robot to move forward instead of backward. You should probably change your escape_vel parameter to be negative^[[0m
^[[33m[ WARN] [1457743141.117449821]: Map update loop missed its desired rate of 5.0000Hz... the loop actually took 2.4833 seconds^[[0m
^[[0m[ INFO] [1457743141.228343349]: Recovery behavior will clear layer obstacles^[[0m
^[[0m[ INFO] [1457743141.295915976]: Recovery behavior will clear layer obstacles^[[0m
^[[33m[ WARN] [1457743143.549180791]: Map update loop missed its desired rate of 5.0000Hz... the loop actually took 2.4317 seconds^[[0m
^[[0m[ INFO] [1457743143.584887743]: odom received!^[[0m
^[[33m[ WARN] [1457743332.059942358]: The origin for the sensor at (55.48, 14.19) is out of map bounds. So, the costmap cannot raytrace for it.^[[0m
^[[33m[ WARN] [1457743561.880260307]: Costmap2DROS transform timeout. Current time: 1457743561.8801, global_pose stamp: 1457743561.5727, tolerance: 0.3000^[[0m
^[[33m[ WARN] [1457743561.880338334]: Could not get robot pose, cancelling reconfiguration^[[0m
^[[33m[ WARN] [1457743562.915057575]: Costmap2DROS transform timeout. Current time: 1457743562.9150, global_pose stamp: 1457743561.5727, tolerance: 0.3000^[[0m
^[[33m[ WARN] [1457743562.915153212]: Could not get robot pose, cancelling reconfiguration^[[0m
^[
```

...

```
[[33m[ WARN] [1457809496.600207867]: Map update loop missed its desired rate of 10.0000Hz... the loop actually took 0.1998 seconds^[[0m
^[[33m[ WARN] [1457809496.711431632]: Control loop missed its desired rate of 10.0000Hz... the loop actually took 0.1230 seconds^[[0m
^[[33m[ WARN] [1457809496.809094271]: Control loop missed its desired rate of 10.0000Hz... the loop actually took 0.1207 seconds^[[0m
^[[33m[ WARN] [1457809496.919299675]: Control loop missed its desired rate of 10.0000Hz... the loop actually took 0.1309 seconds^[[0m
^[[33m[ WARN] [1457809496.919743820]: Map update loop missed its desired rate of 10.0000Hz... the loop actually took 0.4194 seconds^[[0m
^[[33m[ WARN] [1457809497.017091350]: Control loop missed its desired rate of 10.0000Hz... the loop actually took 0.1287 seconds^[[0m
^[[33m[ WARN] [1457809497.125917877]: Control loop missed its desired rate of 10.0000Hz... the loop actually took 0.1375 seconds^[[0m
^[[33m[ WARN] [1457809497.126483342]: Map ^[[0m[ INFO] [1457743136.828834422]: Subscribed to map topic.^[[0m
^[[0m[ INFO] [1457743137.033320141]: Received a 1300 X 1300 map @ 0.050 m/pix
^[[0m
^[[0m[ INFO] [1457743137.094489383]: Initializing likelihood field model; this can take some time on large maps...^[[0m
^[[0m[ INFO] [1457743137.832165766]: Done initializing likelihood field model.^[[0m
^[[33m[ WARN] [1457743331.591620838]: Failed to transform initial pose in time (Lookup would require extrapolation into the future.  Requested time 1457743331.591422593 but the latest data is at time 1457743331.572658220, when looking up transform from frame [map] to frame [base_link])^[[0m
^[[0m[ INFO] [1457743331.591672420]: Setting pose (1457743331.591658): 48.797 12.229 3.142^[[0m
^[[33m[ WARN] [1457743792.800522170]: Failed to transform initial pose in time (Lookup would require extrapolation into the future.  Requested time 1457743792.776796926 but the latest data is at time 1457743792.706005520, when looking up transform from frame [base_link] to frame [map])^[[0m
^[[0m[ INFO] [1457743792.800612245]: Setting pose (1457743792.800570): 52.572 14.564 1.234^[[0m
^[[33m[ WARN] [1457746483.898378024]: Failed to transform initial pose in time (Lookup would require extrapolation into the future.  Requested time 1457746483.876751495 but the latest data is at time 1457746483.806004311, when looking up transform from frame [base_link] to frame [map])^[[0m
^[[0m[ INFO] [1457746483.898425523]: Setting pose (1457746483.898408): 52.574 14.566 -0.061^[[0m
^[[33m[ WARN] [1457762079.209352845]: Failed to transform initial pose in time (Lookup would require extrapolation into the future.  Requested time 1457762079.176601491 but the latest data is at time 1457762079.105837851, when looking up transform from frame [base_link] to frame [map])^[[0m
^[[0m[ INFO] [1457762079.209834705]: Setting pose (1457762079.209795): 52.635 14.584 1.551^[[0m
^[[33m[ WARN] [1457769439.898709658]: Failed to transform initial pose in time (Lookup would require extrapolation into the future.  Requested time 1457769439.876521652 but the latest data is at time 1457769439.805700878, when looking up transform from frame [base_link] to frame [map])^[[0m
^[
```

...

```
[[33m[ WARN] [1457989157.355139470]: Map update loop missed its desired rate of 10.0000Hz... the loop actually took 0.1257 seconds^[[0m
^[[33m[ WARN] [1457989172.093539751]: Control loop missed its desired rate of 10.0000Hz... the loop actually took 0.1051 seconds^[[0m
^[[33m[ WARN] [1457989217.569386814]: Map update loop missed its desired rate of 10.0000Hz... the loop actually took 0.1400 seconds^[[0m
^[[33m[ WARN] [1457989217.690812815]: Control loop missed its desired rate of 10.0000Hz... the loop actually took 0.1021 seconds^[[0m
^[[33m[ WARN] [1457989217.785528584]: Map update loop missed its desired rate of 10.0000Hz... the loop actually took 0.1561 seconds^[[0m
^[[0m[ INFO] [1457989235.080741887]: Using plugin "static_layer"^[[0m
^[[0m[ INFO] [1457989235.181643366]: Requesting the map...^[[0m
^[[0m[ INFO] [1457989235.388470647]: Resizing costmap to 1300 X 1300 at 0.050000 m/pix^[[0m
^[[0m[ INFO] [1457989235.486678993]: Received a 1300 X 1300 map at 0.050000 m/pix^[[0m
^[[0m[ INFO] [1457989235.498871646]: Using plugin "obstacle_layer"^[[0m
^[[0m[ INFO] [1457989235.507666664]:     Subscribed to Topics: velodyne_scan laser_scan_sensor laser_scan_sensor2^[[0m
^[[0m[ INFO] [1457989235.630951278]: Using plugin "inflation_layer"^[[0m
^[[0m[ INFO] [1457989235.837396307]: Using plugin "obstacle_layer"^[[0m
^[[0m[ INFO] [1457989235.896610860]:     Subscribed to Topics: velodyne_scan laser_scan_sensor laser_scan_sensor2^[[0m
^[[0m[ INFO] [1457989235.960775672]: Using plugin "inflation_layer"^[[0m
^[[0m[ INFO] [1457989236.106993043]: Created local_planner base_local_planner/TrajectoryPlannerROS^[[0m
^[[0m[ INFO] [1457989236.121155165]: Sim period is set to 0.10^[[0m
^[[33m[ WARN] [1457989236.147499235]: You've specified a positive escape velocity. This is probably not what you want and will cause the robot to move forward instead of backward. You should probably change your escape_vel parameter to be negative^[[0m
^[[33m[ WARN] [1457989238.283093546]: Map update loop missed its desired rate of 5.0000Hz... the loop actually took 2.5626 seconds^[[0m
^[[0m[ INFO] [1457989238.395917919]: Recovery behavior will clear layer obstacles^[[0m
^[[0m[ INFO] [1457989238.477638535]: Recovery behavior will clear layer obstacles^[[0m
^[[0m[ INFO] [1457989240.810308461]: odom received!^[[0m
^[[33m[ WARN] [1457989240.830434083]: Map update loop missed its desired rate of 5.0000Hz... the loop actually took 2.5474 seconds^[[0m
^[[33m[ WARN] [1457989259.547162379]: Map update loop missed its desired rate of 10.0000Hz... the loop actually took 0.1386 seconds^[[0m
^[[33m[ WARN] [1457989271.438769466]: Map update loop missed its desired rate of 5.0000Hz... the loop actually took 0.4083 seconds^[[0m
^[[33m[ WARN] [1457989271.742303751]: Map update loop missed its desired rate of 5.0000Hz... the loop actually took 0.3035 seconds^[[0m
^[[33m[ WARN] [1457989272.038628930]: Map update loop missed its desired rate of 5.0000Hz... the loop actually took 0.3999 seconds^[[0m
^[[33m[ WARN] [1457989272.326183762]: Map update loop missed its desired rate of 5.0000Hz... the loop actually took 0.4874 seconds^[[0m
^[
```

I can provide the full move-base log if needed. It's pretty big though.

**Comment by ssrselvamraju** [comment]
Agree to @mirzashah's comment. The issue is found in 1.12.6+ and works fine until 1.12.5.

**Comment by alexhenning** [comment]
@ssrselvamraju Could you post the full output of `rosparam get /move_base`

**Comment by ssrselvamraju** [comment]
@alexhenning Here you go:

```
rosparam  get /move_base/
NavfnROS: {allow_unknown: false}
TrajectoryPlannerROS: {acc_lim_th: 9.0, acc_lim_theta: 3.2, acc_lim_x: 3.0, acc_lim_y: 2.5,
  angular_sim_granularity: 0.025, dwa: false, escape_reset_dist: 0.1, escape_reset_theta: 1.57079632679,
  escape_vel: 0.0, gdist_scale: 0.8, heading_lookahead: 0.325, heading_scoring: false,
  heading_scoring_timestep: 0.1, holonomic_robot: false, max_rotational_vel: 0.5,
  max_vel_theta: 1.0, max_vel_x: 0.6, meter_scoring: true, min_in_place_rotational_vel: 0.2,
  min_in_place_vel_theta: 0.4, min_vel_theta: -1.0, min_vel_x: 0.25, occdist_scale: 0.01,
  oscillation_reset_dist: 0.05, pdist_scale: 1.2, restore_defaults: false, sim_granularity: 0.025,
  sim_time: 1.7, simple_attractor: false, vtheta_samples: 20, vx_samples: 20, xy_goal_tolerance: 0.2,
  y_vels: '-0.3,-0.1,0.1,-0.3', yaw_goal_tolerance: 0.25}
aggressive_reset: {reset_distance: 1.84}
base_global_planner: navfn/NavfnROS
base_local_planner: base_local_planner/TrajectoryPlannerROS
clearing_rotation_allowed: true
conservative_reset: {reset_distance: 3.0}
conservative_reset_dist: 3.0
controller_frequency: 10.0
controller_patience: 5.0
global_costmap:
  footprint: '[]'
  footprint_padding: 0.01
  global_frame: map
  height: 10
  inflation_layer: {cost_scaling_factor: 10.0, enabled: true, inflation_radius: 1.6}
  map_cloud: {clearing: true, data_type: PointCloud2, marking: true, sensor_frame: base_link,
    topic: map_pointcloud}
  map_type: costmap
  obstacle_layer:
    combination_method: 1
    enabled: true
    footprint_clearing_enabled: true
    laser_scan_sensor: {clearing: true, data_type: LaserScan, marking: true, sensor_frame: LMS151,
      topic: bottom_scan}
    laser_scan_sensor2: {clearing: true, data_type: LaserScan, marking: true, sensor_frame: TiM551,
      topic: top_scan}
    max_obstacle_height: 2.0
    observation_sources: velodyne_scan laser_scan_sensor laser_scan_sensor2
    obstacle_range: 3.0
    raytrace_range: 5.0
    track_unknown_space: true
    velodyne_scan: {clearing: true, data_type: LaserScan, marking: true, sensor_frame: velodyne,
      topic: velodyne_scan}
  origin_x: 0.0
  origin_y: 0.0
  plugins:
  - {name: static_layer, type: 'costmap_2d::StaticLayer'}
  - {name: obstacle_layer, type: 'costmap_2d::ObstacleLayer'}
  - {name: inflation_layer, type: 'costmap_2d::InflationLayer'}
  publish_frequency: 0.0
  resolution: 0.05
  robot_base_frame: base_link
  robot_radius: 0.5
  static_layer: {enabled: true, track_unknown_space: true, unknown_cost_value: 253}
  static_map: true
  transform_tolerance: 0.3
  update_frequency: 5.0
  width: 10
local_costmap:
  footprint: '[]'
  footprint_padding: 0.01
  global_frame: map
  height: 8
  inflation_layer: {cost_scaling_factor: 0.0, enabled: true, inflation_radius: 1.6}
  map_cloud: {clearing: true, data_type: PointCloud2, marking: true, sensor_frame: base_link,
    topic: map_pointcloud}
  map_type: costmap
  obstacle_layer:
    combination_method: 1
    enabled: true
    footprint_clearing_enabled: true
    laser_scan_sensor: {clearing: true, data_type: LaserScan, marking: true, sensor_frame: LMS151,
      topic: bottom_scan}
    laser_scan_sensor2: {clearing: true, data_type: LaserScan, marking: true, sensor_frame: TiM551,
      topic: top_scan}
    max_obstacle_height: 2.0
    observation_sources: velodyne_scan laser_scan_sensor laser_scan_sensor2
    obstacle_range: 3.0
    raytrace_range: 5.0
    velodyne_scan: {clearing: true, data_type: LaserScan, marking: true, sensor_frame: velodyne,
      topic: velodyne_scan}
  origin_x: 0.0
  origin_y: 0.0
  plugins:
  - {name: obstacle_layer, type: 'costmap_2d::ObstacleLayer'}
  - {name: inflation_layer, type: 'costmap_2d::InflationLayer'}
  publish_frequency: 5.0
  resolution: 0.05
  robot_base_frame: base_link
  robot_radius: 0.5
  rolling_window: true
  static_map: false
  transform_tolerance: 0.3
  update_frequency: 10.0
  width: 8
oscillation_distance: 0.5
oscillation_timeout: 0.0
planner_frequency: 0.5
planner_patience: 5.0
recovery_behavior_enabled: false
restore_defaults: false
shutdown_costmaps: false
```

**Comment by alexhenning** [comment]
@ssrselvamraju ran the following launch file on one of our robots with 1.12.6 installed from debs and a source checkout of 1.12.7 and I was unable to reproduce it. What are you using to serve the map? Is it possible that something has changed with that? The best way to move forward be to use a source check and run [git bisect](https://git-scm.com/docs/git-bisect) to try to isolate the commit that breaks things and we can look at that. In terms of me reproducing things, it would be helpful if you could provide more details on exactly what you're running and steps to reproduce the problem.

move_base.launch

``` xml
<launch>
  <!-- set topics -->
  <arg name="map_topic" default="map" />
  <arg name="cmd_vel_topic" default="cmd_vel" />
  <arg name="odom_topic" default="odom" />

  <!-- planners, costmaps, etc -->
  <node pkg="move_base" type="move_base" name="move_base" respawn="true" output="screen">
    <rosparam file="path/to/config.yaml" command="load" ns="/" />
    <remap from="cmd_vel" to="$(arg cmd_vel_topic)"/>
    <remap from="odom" to="$(arg odom_topic)"/>
    <remap from="map" to="$(arg map_topic)" />
  </node>
</launch>
```

config.yaml

``` yaml
move_base:
  NavfnROS: {allow_unknown: false}
  TrajectoryPlannerROS: {acc_lim_th: 9.0, acc_lim_theta: 3.2, acc_lim_x: 3.0, acc_lim_y: 2.5,
  angular_sim_granularity: 0.025, dwa: false, escape_reset_dist: 0.1, escape_reset_theta: 1.57079632679,
  escape_vel: 0.0, gdist_scale: 0.8, heading_lookahead: 0.325, heading_scoring: false,
  heading_scoring_timestep: 0.1, holonomic_robot: false, max_rotational_vel: 0.5,
  max_vel_theta: 1.0, max_vel_x: 0.6, meter_scoring: true, min_in_place_rotational_vel: 0.2,
  min_in_place_vel_theta: 0.4, min_vel_theta: -1.0, min_vel_x: 0.25, occdist_scale: 0.01,
  oscillation_reset_dist: 0.05, pdist_scale: 1.2, restore_defaults: false, sim_granularity: 0.025,
  sim_time: 1.7, simple_attractor: false, vtheta_samples: 20, vx_samples: 20, xy_goal_tolerance: 0.2,
  y_vels: '-0.3,-0.1,0.1,-0.3', yaw_goal_tolerance: 0.25}
  aggressive_reset: {reset_distance: 1.84}
  base_global_planner: navfn/NavfnROS
  base_local_planner: base_local_planner/TrajectoryPlannerROS
  clearing_rotation_allowed: true
  conservative_reset: {reset_distance: 3.0}
  conservative_reset_dist: 3.0
  controller_frequency: 10.0
  controller_patience: 5.0
  global_costmap:
    footprint: '[]'
    footprint_padding: 0.01
    global_frame: map
    height: 10
    inflation_layer: {cost_scaling_factor: 10.0, enabled: true, inflation_radius: 1.6}
    map_cloud: {clearing: true, data_type: PointCloud2, marking: true, sensor_frame: base_link,
      topic: map_pointcloud}
    map_type: costmap
    obstacle_layer:
      combination_method: 1
      enabled: true
      footprint_clearing_enabled: true
      laser_scan_sensor: {clearing: true, data_type: LaserScan, marking: true, sensor_frame: LMS151,
        topic: bottom_scan}
      laser_scan_sensor2: {clearing: true, data_type: LaserScan, marking: true, sensor_frame: TiM551,
        topic: top_scan}
      max_obstacle_height: 2.0
      observation_sources: velodyne_scan laser_scan_sensor laser_scan_sensor2
      obstacle_range: 3.0
      raytrace_range: 5.0
      track_unknown_space: true
      velodyne_scan: {clearing: true, data_type: LaserScan, marking: true, sensor_frame: velodyne,
        topic: velodyne_scan}
    origin_x: 0.0
    origin_y: 0.0
    plugins:
    - {name: static_layer, type: 'costmap_2d::StaticLayer'}
    - {name: obstacle_layer, type: 'costmap_2d::ObstacleLayer'}
    - {name: inflation_layer, type: 'costmap_2d::InflationLayer'}
    publish_frequency: 0.0
    resolution: 0.05
    robot_base_frame: base_link
    robot_radius: 0.5
    static_layer: {enabled: true, track_unknown_space: true, unknown_cost_value: 253}
    static_map: true
    transform_tolerance: 0.3
    update_frequency: 5.0
    width: 10
  local_costmap:
    footprint: '[]'
    footprint_padding: 0.01
    global_frame: map
    height: 8
    inflation_layer: {cost_scaling_factor: 0.0, enabled: true, inflation_radius: 1.6}
    map_cloud: {clearing: true, data_type: PointCloud2, marking: true, sensor_frame: base_link,
      topic: map_pointcloud}
    map_type: costmap
    obstacle_layer:
      combination_method: 1
      enabled: true
      footprint_clearing_enabled: true
      laser_scan_sensor: {clearing: true, data_type: LaserScan, marking: true, sensor_frame: LMS151,
        topic: bottom_scan}
      laser_scan_sensor2: {clearing: true, data_type: LaserScan, marking: true, sensor_frame: TiM551,
        topic: top_scan}
      max_obstacle_height: 2.0
      observation_sources: velodyne_scan laser_scan_sensor laser_scan_sensor2
      obstacle_range: 3.0
      raytrace_range: 5.0
      velodyne_scan: {clearing: true, data_type: LaserScan, marking: true, sensor_frame: velodyne,
        topic: velodyne_scan}
    origin_x: 0.0
    origin_y: 0.0
    plugins:
    - {name: obstacle_layer, type: 'costmap_2d::ObstacleLayer'}
    - {name: inflation_layer, type: 'costmap_2d::InflationLayer'}
    publish_frequency: 5.0
    resolution: 0.05
    robot_base_frame: base_link
    robot_radius: 0.5
    rolling_window: true
    static_map: false
    transform_tolerance: 0.3
    update_frequency: 10.0
    width: 8
  oscillation_distance: 0.5
  oscillation_timeout: 0.0
  planner_frequency: 0.5
  planner_patience: 5.0
  recovery_behavior_enabled: false
  restore_defaults: false
  shutdown_costmaps: false
```

```
shell1 $ roslaunch move_base.launch
shell2 $ roslaunch map # Either map server or slam
shell3 $ rosservice call /move_base/clear_costmaps "{}"  # Called lots of times
```
