### ISSUE TITLE
Dwa failed to produce path in free space

### ISSUE THREAD

**Issue by drscopus** [ros-planning/navigation#651]
Hi, all. I found a bug for dwa local planner. When the goal is in the -x and -y direction with respect to robot's current pose, the robot moves really slowly, even stop.

For example, the right part of the following image shows the case that the robot stops in the way to a goal as the end of blue line (not dotted blue lines) shows. The left part of the following image shows the output in the terminal while the package is being run in debug model.

It outputs "The dwa local planner failed to find a valid plan, cost functions discarded all candidates. This can mean there is an obstacle too close to the robot". This information is generated from [here ](https://github.com/ros-planning/navigation/blob/indigo-devel/dwa_local_planner/src/dwa_planner_ros.cpp#L216)when the cost of computed path is smaller than zero.

Obviously, we can see that there is no obstacle around the robot at that time. Please note that this case can be repeated as long as we want.

![dwa_failed_in_free_space](https://user-images.githubusercontent.com/9296543/35312465-8967f3e4-00f6-11e8-85cf-def89deb8f7a.jpg)

The parameters are listed as follows:

```
DWAPlannerROS:

# Robot Configuration Parameters - Kobuki
  max_vel_x: 0.3  # 0.55
  min_vel_x: 0.0 

  max_vel_y: 0.0  # diff drive robot
  min_vel_y: 0.0  # diff drive robot

  max_trans_vel: 0.3 # choose slightly less than the base's capability
  min_trans_vel: 0.04  # this is the min trans velocity when there is negligible rotational velocity
  trans_stopped_vel: 0.1

  max_rot_vel: 1.57 # default 5.0  # choose slightly less than the base's capability
  min_rot_vel: 0.4  # this is the min angular velocity when there is negligible translational velocity
  rot_stopped_vel: 0.4

  acc_lim_x: 1.0 # maximum is theoretically 2.0, but we 
  acc_lim_theta: 2.0
  acc_lim_y: 0.0      # diff drive robot

 # Goal Tolerance Parameters


 yaw_goal_tolerance: 0.05  # 0.05
  xy_goal_tolerance: 0.05 # 0.10
  # latch_xy_goal_tolerance: false

# Forward Simulation Parameters
  sim_time: 1.7  #1.5       # 1.7
  vx_samples: 20      # 3
  vy_samples: 1   #1       # diff drive robot, there is only one sample
  vtheta_samples: 40  # 20

# Trajectory Scoring Parameters
  path_distance_bias: 32.0      # 32.0   - weighting for how much it should stick to the global path plan
  goal_distance_bias: 12.0      # 24.0   - wighting for how much it should attempt to reach its goal
  occdist_scale: 0.02           # 0.01   - weighting for how much the controller should avoid obstacles
  forward_point_distance: 0.325 #0.325 # 0.325  - how far along to place an additional scoring point
  stop_time_buffer: 0.2         # 0.2    - amount of time a robot must stop in before colliding for a valid traj.
  scaling_speed: 0.25           # 0.25   - absolute velocity at which to start scaling the robot's footprint
  max_scaling_factor: 0.2       # 0.2    - how much to scale the robot's footprint when at speed.

# Oscillation Prevention Parameters
  oscillation_reset_dist: 0.05  # 0.05   - how far to travel before resetting oscillation flags

# Debugging
  publish_traj_pc : true
  publish_cost_grid_pc: true
  global_frame_id: odom
# Differential-drive robot configuration - necessary?
  holonomic_robot: false
```

looking forward anyone can give me any advice to solve this problem! Thank you!
