### ISSUE TITLE
costmap2d does not respect yaw in map origin parameter.

### ISSUE THREAD

**Issue by positron96** [ros-planning/navigation#661]
Hello. I am trying to start a move_base with global costmap loaded from map_server node. The map has origin rotated, the file map.yaml is as follows:
```
image: file.png
resolution: 0.0333
origin: [0, 0, 1]
occupied_thresh: 0.6
free_thresh: 0.2
negate: 0
```

Relevant parts of global costmap config are the following:
```
global_costmap:
  global_frame: /map
  robot_base_frame: base_link
  update_frequency: 4.0
  publish_frequency: 2
  static_map: true

  cost_scaling_factor: 12
  
  
  width: 40.0
  height: 40.0
  resolution: 0.20
  origin_x: 0.0
  origin_y: 0.0

  map_topic: /map
```

When I start, /map topic looks as it should (rotated) but global costmap is not rotated at all.

![virtualbox_ubox_15_02_2018_18_12_53](https://user-images.githubusercontent.com/2095278/36254122-6a48a9da-127c-11e8-9344-acca331650c1.png)

Is it the supposed behavior? Can I fix my config to respect rotation?
