### ISSUE TITLE
The clearing stays permanent in obstacle costmap, when 0 (overwrite) combination method is applied

### ISSUE THREAD

**Issue by anslex** [ros-planning/navigation#736]
> available on ros answers also:
> https://answers.ros.org/question/292822/why-the-clearing-stays-permanent-in-obstacle-costmap-when-0-overwrite-combination-method-is-applied/

Hello !

I am clearing some layers markings by a layer with a detected object to be cleared and the problem is that its' clearing stay permanent even when the object disappeares.

So here more detailed information:

The goal:

-    Erase any markings on the costmap under x_object when it is detected
-    Continue marking with laser layers when the x_object is disappeared or was not present

The actual results:

-    The laser layers mark the obstacles. Perfect ! =)
-    The x_object detected and overwrites (erases) the markings. Perfect ! =)
-    The x_object disappeares (goes away) Perfect ! =)
-    The laser layers do not mark anymore where was detected the x_object. Bad ! =(

I tried different observation_persistence values:

   0.0 to have only recent measurements (expected them to be available only during one cycle of observation)
    values > 0.0 to keep the observation during some time and refresh the clearings after

Code:

```
x_obstacle_clearing_layer:
  enabled: true
  observation_sources: x_object_clearing_cloud
  combination_method: 0

x_object_clearing_cloud:
  sensor_frame: base_footprint
  data_type: PointCloud2
  topic: /detect_x_object/object
  expected_update_rate: 2.0
  observation_persistence: 1.0
  marking: false
  clearing: true
  raytrace_range: 5.3
  obstacle_range: 4.8
  min_obstacle_height: -2.0
  max_obstacle_height: 2.0
```

Thank you !

P.S.: Working with ROS Kinetic
