### ISSUE TITLE
Discouraging move_base planner's preference for long curved trajectories

### ISSUE THREAD

**Issue by sabetAI** [ros-planning/navigation#781]
In tight hallway environments, move_base's planner **always** gets the robot stuck in the walls' costmap attempting silly smooth curved trajectories instead of choosing in-place rotations at appropriate place. When the robot gets stuck in a costmap, which it inevitably does, it doesn't attempt new trajectories. How can I fix this pathological behaviour?

```
TrajectoryPlannerROS:

  # Robot Configuration Parameters
  acc_lim_x: 2.0
  acc_lim_theta:  2.0

  max_vel_x: 0.15
  min_vel_x: 0.09

  max_vel_theta: 1.2
  min_vel_theta: -1.2
  min_in_place_vel_theta: 0.15

  holonomic_robot: false
  escape_vel: -0.2

  # Goal Tolerance Parameters
  yaw_goal_tolerance: 0.3
  xy_goal_tolerance: 0.3
  latch_xy_goal_tolerance: false

  # Forward Simulation Parameters
  sim_time: 10.0
  sim_granularity: 0.02
  angular_sim_granularity: 0.02
  vx_samples: 20
  vtheta_samples: 20
  controller_frequency: 10.0

  # Trajectory scoring parameters
  meter_scoring: true # Whether the gdist_scale and pdist_scale parameters should assume that goal_distance and path_distance are expressed in units of meters or cells. Cells are assumed by default (false).
  occdist_scale:  1.0 #The weighting for how much the controller should attempt to avoid obstacles. default 0.01
  pdist_scale: 0.75  #    The weighting for how much the controller should stay close to the path it was given . default 0.6
  gdist_scale: 0.9 #     The weighting for how much the controller should attempt to reach its local goal, also controls speed  default 0.8

  heading_lookahead: 0.325  #How far to look ahead in meters when scoring different in-place-rotation trajectories
  heading_scoring: false  #Whether to score based on the robot's heading to the path or its distance from the path. default false
  heading_scoring_timestep: 0.7   #How far to look ahead in time in seconds along the simulated trajectory when using heading scoring (double, default: 0.8)
  dwa: true #Whether to use the Dynamic Window Approach (DWA)_ or whether to use Trajectory Rollout
  simple_attractor: false
  publish_cost_grid_pc: true

  #Oscillation Prevention Parameters
  oscillation_reset_dist: 0.05 #How far the robot must travel in meters before oscillation flags are reset (double, default: 0.05)
  escape_reset_dist: 0.1
  escape_reset_theta: 0.1
shutdown_costmaps: false

controller_frequency: 10.0
controller_patience: 15.0

planner_frequency: 10.0
planner_patience: 5.0

oscillation_timeout: 5.0
oscillation_distance: 0.5

recovery_behavior_enabled: true
clearing_rotation_allowed: true
map_type: costmap
origin_z: 0.0
z_resolution: 1
z_voxels: 2

obstacle_range: 2.5
raytrace_range: 3.0

publish_voxel_map: false
transform_tolerance: 0.5
meter_scoring: true

footprint: [[-0.21, -0.165], [-0.21, 0.165], [0.21, 0.165], [0.21, -0.165]]
footprint_padding: 0.04

plugins:
- {name: obstacles_layer, type: "costmap_2d::ObstacleLayer"}
- {name: inflater_layer, type: "costmap_2d::InflationLayer"}

obstacles_layer:
  observation_sources: scan
  scan: {sensor_frame: front_laser, data_type: LaserScan, topic: /scan, marking: true, clearing: true, min_obstacle_height: -2.0, max_obstacle_height: 2.0, obstacle_range: 2.5, raytrace_range: 3.0}

inflater_layer:
 inflation_radius: 0.035
global_costmap:
   global_frame: map
   robot_base_frame: base_link
   update_frequency: 10.0
   publish_frequency: 5.0
   width: 40.0
   height: 40.0
   resolution: 0.02
   origin_x:  0.0
   origin_y:  0.0
   static_map: true
   rolling_window: false

   plugins:
   - {name: static_layer, type: "costmap_2d::StaticLayer"}
   - {name: obstacles_layer, type: "costmap_2d::ObstacleLayer"}
   - {name: inflater_layer, type: "costmap_2d::InflationLayer"}
local_costmap:
   global_frame: map
   robot_base_frame: base_link
   update_frequency: 10.0
   publish_frequency: 5.0
   width: 10.0
   height: 10.0
   resolution: 0.02
   static_map: false
   rolling_window: true

```
