### ISSUE TITLE
Global costmap cleared from time to time

### ISSUE THREAD

**Issue by ghost** [ros-planning/navigation#783]
The whole navigation stack breaks down every time the global costmap is cleared (and restored on the next publish interval).
![output_qeetm2](https://user-images.githubusercontent.com/90824/44816594-f66b8400-abe2-11e8-9cfb-6a7da338070d.gif)

I am on the branch kinetic:develop.
There is also a warning in the stdout from mapUpdateLoop
```
Map update loop missed its desired rate of 2.5000Hz... the loop actually took 0.9068 seconds'
```
**Update**: Looks like this is related to this issue: https://github.com/ros-planning/navigation/issues/320
Thank you very much in advance!

Just in case, the parameters used:

* Global costmap params:
```
global_costmap:
  global_frame: /map
  robot_base_frame: /base_link #/base_footprint for simulation
  update_frequency: 2.5
  publish_frequency: 9
  always_send_full_costmap: true #true
  static_map: true
  transform_tolerance: 1.5  # 1.5 #latency in sec
    
  plugins:
    - {name: static_layer,            type: "costmap_2d::StaticLayer"}
    - {name: prohibition_layer,       type: "costmap_prohibition_layer_namespace::CostmapProhibitionLayer"}
    - {name: obstacle_layer,          type: "costmap_2d::VoxelLayer"}
    - {name: inflation_layer,         type: "costmap_2d::InflationLayer"}

  static_layer:
    map_topic: /map
    track_unknown_space: true   # must be true in order to avoid path planning through unknown space
    lethal_cost_threshold: 65   # 60, 1 #from colorpicking the raw map topic, i would say 66
    subscribe_to_updates: true
```

* Move base params:
```
shutdown_costmaps: false

controller_frequency: 12.0
controller_patience: 3.0


planner_frequency: 1.0
planner_patience: 1.0

oscillation_timeout: 10.0
oscillation_distance: 0.2

# local planner - default is trajectory rollout
base_local_planner: "dwa_local_planner/DWAPlannerROS"

base_global_planner: "navfn/NavfnROS" #alternatives: global_planner/GlobalPlanner, carrot_planner/CarrotPlanner

recovery_behaviors:
  - {name: conservative_reset, type: clear_costmap_recovery/ClearCostmapRecovery}
  - {name: aggressive_reset, type: clear_costmap_recovery/ClearCostmapRecovery}

conservative_reset:
  layer_names: ["obstacle_layer"]
  reset_distance: 3.0

aggressive_reset:
  layer_names: ["obstacle_layer"]
  reset_distance: 1.9
```
